services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.flask
    image: flask0.1
  client:
    build:
      context: .
      dockerfile: Dockerfile.react
    image: react0.1
    ports:
      - "3000:80"
